# Generated by Django 5.0.1 on 2024-02-06 07:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_products_is_sale_products_sale_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 2, 6, 11, 14, 25, 463892)),
        ),
    ]
